import { Slide } from '../types';
import { Slide1, Slide2, Slide3, Slide3a, Slide3b, Slide4, Slide5, Slide6, Slide7, Slide8, Slide9, Slide10 } from './part1';
import { Slide11, Slide12, Slide13, Slide14, Slide15, Slide16, Slide17, Slide18, Slide19, Slide20 } from './part2';
import { Slide21, Slide21a, Slide21b, Slide21c, Slide22, Slide23, Slide24, Slide25, Slide26, Slide27, Slide28, Slide29, Slide30 } from './part3';
import { Slide31, Slide32, Slide33 } from './part4';
import { Slide34, Slide35, Slide36, Slide37, Slide38 } from './part5';
import { Slide39, Slide40, Slide41, Slide42, Slide43, Slide44 } from './part6';
import { Slide45, Slide46, Slide46a, Slide47, Slide48, Slide49, Slide49a, Slide50 } from './part7';
import { Slide50a, Slide51, Slide52, Slide53, Slide53a, Slide54, Slide55, Slide55a, Slide56, Slide56a, Slide56b, Slide57, Slide58 } from './part8';
import { Slide59, Slide60, Slide61, Slide62, Slide63, Slide63a, Slide63b, Slide64 } from './part9';
import { Slide65, Slide66, Slide67, Slide68, Slide69, Slide70, Slide71, Slide72, Slide73, Slide74 } from './part10';
import { Slide75, Slide76, Slide77, Slide78, Slide79, Slide80, Slide81, Slide82, Slide83, Slide83a, Slide84 } from './part11';
import { Slide85, Slide86, Slide87, Slide88, Slide89, Slide90, Slide91, Slide92, Slide93, Slide93a, Slide94 } from './part12';
import { Slide95, Slide96, Slide97, Slide98, Slide99, Slide100, Slide101, Slide102, Slide103, Slide104 } from './part13';
import { Slide105, Slide106, Slide107, Slide108, Slide109, Slide110, Slide111, Slide112, Slide113, Slide114 } from './part14';
import { Slide115, Slide116, Slide117, Slide118, Slide119, Slide120, Slide121, Slide121a, Slide121b, Slide122, Slide122a, Slide123, Slide124 } from './part15';
import { Slide125, Slide125a, Slide126, Slide127, Slide128, Slide129, Slide130, Slide131, Slide132, Slide133, Slide134 } from './part16';
import { Slide135, Slide136, Slide137, Slide138, Slide139, Slide140, Slide141, Slide142, Slide143, Slide143a, Slide143b, Slide144 } from './part17';
import { Slide145, Slide146, Slide147, Slide148, Slide149, Slide150, Slide151, Slide152, Slide153, Slide154 } from './part18';
import { Slide155, Slide156, Slide157, Slide158, Slide158a, Slide159, Slide160, Slide161, Slide162, Slide163, Slide164 } from './part19';
import { Slide165, Slide166, Slide167, Slide168, Slide169, Slide170, Slide170a, Slide170b, Slide171, Slide172, Slide173 } from './part20';
import { Slide174, Slide175, Slide176, Slide177, Slide178, Slide179, Slide180 } from './part21';
import { Slide181, Slide182, Slide183, Slide184, Slide185, Slide186, Slide187, Slide188, Slide189, Slide190 } from './part22';
import { Slide191, Slide192, Slide193, Slide194, Slide195, Slide196, Slide197, Slide198, Slide199, Slide200 } from './part23';

export const slides: Slide[] = [
  { id: 's1', title: 'Portada', section: '1.1. Metodología', component: Slide1 },
  { id: 's2', title: '1.1.1. Introducción al ML', section: '1.1. Metodología', component: Slide2 },
  { id: 's3', title: 'Modelos Teóricos vs Empíricos', section: '1.1. Metodología', component: Slide3 },
  { id: 's3a', title: 'Código: Modelos Teóricos', section: '1.1. Metodología', component: Slide3a },
  { id: 's3b', title: 'Código: Modelos Empíricos', section: '1.1. Metodología', component: Slide3b },
  { id: 's4', title: 'Minería de Datos', section: '1.1. Metodología', component: Slide4 },
  { id: 's5', title: 'Metodologías', section: '1.1. Metodología', component: Slide5 },
  { id: 's6', title: '1.1.2. KDD vs CRISP-DM', section: '1.1. Metodología', component: Slide6 },
  { id: 's7', title: 'La metodología CRISP-DM', section: '1.1. Metodología', component: Slide7 },
  { id: 's8', title: '1.1.3. Fases de CRISP-DM', section: '1.1. Metodología', component: Slide8 },
  { id: 's9', title: 'Ciclo de Vida (Interactivo)', section: '1.1. Metodología', component: Slide9 },
  { id: 's10', title: 'Roles en Ciencia de Datos', section: '1.1. Metodología', component: Slide10 },
  { id: 's11', title: 'Rol: Director Técnico', section: '1.1. Metodología', component: Slide11 },
  { id: 's12', title: 'Rol: Científico de Datos', section: '1.1. Metodología', component: Slide12 },
  { id: 's13', title: 'Rol: Analista de Datos', section: '1.1. Metodología', component: Slide13 },
  { id: 's14', title: 'Rol: Ingeniero de Datos', section: '1.1. Metodología', component: Slide14 },
  { id: 's15', title: '1.1.4. Comprensión del Negocio', section: '1.1. Metodología', component: Slide15 },
  { id: 's16', title: 'Tareas Genéricas (Negocio)', section: '1.1. Metodología', component: Slide16 },
  { id: 's17', title: '1.1.5. Comprensión de los Datos', section: '1.1. Metodología', component: Slide17 },
  { id: 's18', title: 'Tareas Genéricas (Datos)', section: '1.1. Metodología', component: Slide18 },
  { id: 's19', title: '1.1.6. Preparación de los Datos', section: '1.1. Metodología', component: Slide19 },
  { id: 's20', title: 'Tareas Genéricas (Prep I)', section: '1.1. Metodología', component: Slide20 },
  { id: 's21', title: 'Tareas Genéricas (Prep II)', section: '1.1. Metodología', component: Slide21 },
  { id: 's21a', title: 'Código: Procesamiento de Imágenes', section: '1.1. Metodología', component: Slide21a },
  { id: 's21b', title: 'Código: Extracción de Características', section: '1.1. Metodología', component: Slide21b },
  { id: 's21c', title: 'Código: Segmentación Avanzada', section: '1.1. Metodología', component: Slide21c },
  { id: 's22', title: '1.1.7. Modelado', section: '1.1. Metodología', component: Slide22 },
  { id: 's23', title: 'Selección de algoritmos', section: '1.1. Metodología', component: Slide23 },
  { id: 's24', title: 'Cajas Blancas vs Cajas Negras', section: '1.1. Metodología', component: Slide24 },
  { id: 's25', title: 'Diseño Experimental', section: '1.1. Metodología', component: Slide25 },
  { id: 's26', title: 'Construir y Evaluar', section: '1.1. Metodología', component: Slide26 },
  { id: 's27', title: '1.1.8. Evaluación', section: '1.1. Metodología', component: Slide27 },
  { id: 's28', title: 'Tareas Genéricas (Evaluación)', section: '1.1. Metodología', component: Slide28 },
  { id: 's29', title: '1.1.9. Despliegue', section: '1.1. Metodología', component: Slide29 },
  { id: 's30', title: 'Tareas Genéricas (Despliegue)', section: '1.1. Metodología', component: Slide30 },
  { id: 's31', title: 'Resumen Interactivo', section: '1.1. Metodología', component: Slide31 },
  { id: 's32', title: 'Quiz: Fases', section: '1.1. Metodología', component: Slide32 },
  { id: 's33', title: 'Quiz: Roles', section: '1.1. Metodología', component: Slide33 },
  { id: 's34', title: '1.2. Tipos de Aprendizaje', section: '1.2. Tipos de Aprendizaje', component: Slide34 },
  { id: 's35', title: '1.2.1. Aprendizaje Supervisado', section: '1.2. Tipos de Aprendizaje', component: Slide35 },
  { id: 's36', title: 'Regresión vs Clasificación', section: '1.2. Tipos de Aprendizaje', component: Slide36 },
  { id: 's37', title: 'Interactivo: Crea tu modelo', section: '1.2. Tipos de Aprendizaje', component: Slide37 },
  { id: 's38', title: 'Quiz: Supervisado', section: '1.2. Tipos de Aprendizaje', component: Slide38 },
  { id: 's39', title: '1.2.2. Aprendizaje No Supervisado', section: '1.2. Tipos de Aprendizaje', component: Slide39 },
  { id: 's40', title: 'Clustering (Interactivo)', section: '1.2. Tipos de Aprendizaje', component: Slide40 },
  { id: 's41', title: 'Reglas de Asociación', section: '1.2. Tipos de Aprendizaje', component: Slide41 },
  { id: 's42', title: '1.2.3. Otros Tipos de Aprendizaje', section: '1.2. Tipos de Aprendizaje', component: Slide42 },
  { id: 's43', title: 'Quiz: Tipos de Aprendizaje', section: '1.2. Tipos de Aprendizaje', component: Slide43 },
  { id: 's44', title: 'Evaluación Final Capítulo 1', section: '1.2. Tipos de Aprendizaje', component: Slide44 },
  { id: 's45', title: '1.3. Estructura de Datos', section: '1.3. Estructura de Datos', component: Slide45 },
  { id: 's46', title: '1.3.1. Estructuras y Tipos', section: '1.3. Estructura de Datos', component: Slide46 },
  { id: 's46a', title: 'Código: Estructuras de Datos', section: '1.3. Estructura de Datos', component: Slide46a },
  { id: 's47', title: '1.3.2. Nomenclatura (X, y)', section: '1.3. Estructura de Datos', component: Slide47 },
  { id: 's48', title: 'Interactivo: Matriz', section: '1.3. Estructura de Datos', component: Slide48 },
  { id: 's49', title: '1.3.3. Características de Datasets', section: '1.3. Estructura de Datos', component: Slide49 },
  { id: 's49a', title: 'Código: Estadística Descriptiva', section: '1.3. Estructura de Datos', component: Slide49a },
  { id: 's50', title: 'Quiz: Estructura', section: '1.3. Estructura de Datos', component: Slide50 },
  { id: 's50a', title: 'La API de Scikit-Learn', section: '1.4. Limpieza de Datos', component: Slide50a },
  { id: 's51', title: '1.4. Limpieza de Datos', section: '1.4. Limpieza de Datos', component: Slide51 },
  { id: 's52', title: '1.4.1. Valores Ausentes', section: '1.4. Limpieza de Datos', component: Slide52 },
  { id: 's53', title: 'Interactivo: Nulos', section: '1.4. Limpieza de Datos', component: Slide53 },
  { id: 's53a', title: 'Código: Imputación de Datos', section: '1.4. Limpieza de Datos', component: Slide53a },
  { id: 's54', title: '1.4.2. Valores Atípicos (Outliers)', section: '1.4. Limpieza de Datos', component: Slide54 },
  { id: 's55', title: 'Detección de Outliers', section: '1.4. Limpieza de Datos', component: Slide55 },
  { id: 's55a', title: 'Código: Detección de Outliers', section: '1.4. Limpieza de Datos', component: Slide55a },
  { id: 's56', title: '1.4.3. Escalado de Datos', section: '1.4. Limpieza de Datos', component: Slide56 },
  { id: 's56a', title: 'Código: Escalado de Datos', section: '1.4. Limpieza de Datos', component: Slide56a },
  { id: 's56b', title: 'Código: Selección de Atributos', section: '1.4. Limpieza de Datos', component: Slide56b },
  { id: 's57', title: '1.4.4. Codificación Categórica', section: '1.4. Limpieza de Datos', component: Slide57 },
  { id: 's58', title: 'Quiz: Limpieza', section: '1.4. Limpieza de Datos', component: Slide58 },
  { id: 's59', title: '1.5. Evaluación de Modelos', section: '1.5. Evaluación de Modelos', component: Slide59 },
  { id: 's60', title: '1.5.1. Particionado de Datos', section: '1.5. Evaluación de Modelos', component: Slide60 },
  { id: 's61', title: '1.5.2. Overfitting y Underfitting', section: '1.5. Evaluación de Modelos', component: Slide61 },
  { id: 's62', title: '1.5.3. Validación Cruzada', section: '1.5. Evaluación de Modelos', component: Slide62 },
  { id: 's63', title: '1.5.4. Métricas de Rendimiento', section: '1.5. Evaluación de Modelos', component: Slide63 },
  { id: 's63a', title: 'Código: Métricas de Regresión', section: '1.5. Evaluación de Modelos', component: Slide63a },
  { id: 's63b', title: 'Código: Métricas de Clasificación', section: '1.5. Evaluación de Modelos', component: Slide63b },
  { id: 's64', title: 'Evaluación Final: Capítulo 1', section: '1.5. Evaluación de Modelos', component: Slide64 },
  { id: 's65', title: 'Capítulo 2: Validación y Evaluación', section: '2.1. Validación hold-out', component: Slide65 },
  { id: 's66', title: 'Introducción a la Validación', section: '2.1. Validación hold-out', component: Slide66 },
  { id: 's67', title: 'Entrenamiento vs. Test', section: '2.1. Validación hold-out', component: Slide67 },
  { id: 's68', title: 'Sobreajuste y Subajuste', section: '2.1. Validación hold-out', component: Slide68 },
  { id: 's69', title: 'Interactivo: Curva de Complejidad', section: '2.1. Validación hold-out', component: Slide69 },
  { id: 's70', title: '2.1. Validación hold-out', section: '2.1. Validación hold-out', component: Slide70 },
  { id: 's71', title: 'Hold-out: Aleatorio vs Secuencial', section: '2.1. Validación hold-out', component: Slide71 },
  { id: 's72', title: 'Interactivo: Simulador Hold-out', section: '2.1. Validación hold-out', component: Slide72 },
  { id: 's73', title: 'Ventajas y Desventajas', section: '2.1. Validación hold-out', component: Slide73 },
  { id: 's74', title: 'Quiz: Validación Hold-out', section: '2.1. Validación hold-out', component: Slide74 },
  { id: 's75', title: 'Hold-out en Python', section: '2.1. Validación hold-out', component: Slide75 },
  { id: 's76', title: 'Análisis del Código Hold-out', section: '2.1. Validación hold-out', component: Slide76 },
  { id: 's77', title: 'El Problema de la Representatividad', section: '2.1. Validación hold-out', component: Slide77 },
  { id: 's78', title: '2.2. Validación Cruzada', section: '2.2. Validación cruzada', component: Slide78 },
  { id: 's79', title: 'Interactivo: K-Fold', section: '2.2. Validación cruzada', component: Slide79 },
  { id: 's80', title: 'Elección de K y LOOCV', section: '2.2. Validación cruzada', component: Slide80 },
  { id: 's81', title: 'Validación Estratificada', section: '2.2. Validación cruzada', component: Slide81 },
  { id: 's82', title: 'Interactivo: Estratificación', section: '2.2. Validación cruzada', component: Slide82 },
  { id: 's83', title: 'Código: Validación Cruzada', section: '2.2. Validación cruzada', component: Slide83 },
  { id: 's83a', title: 'Código: Bootstrapping', section: '2.2. Validación cruzada', component: Slide83a },
  { id: 's84', title: 'Quiz: Validación Cruzada', section: '2.2. Validación cruzada', component: Slide84 },
  { id: 's85', title: '2.3. Ajuste de parámetros', section: '2.3. Ajuste de parámetros', component: Slide85 },
  { id: 's86', title: 'El peligro de ajustar con Test', section: '2.3. Ajuste de parámetros', component: Slide86 },
  { id: 's87', title: 'El Conjunto de Validación', section: '2.3. Ajuste de parámetros', component: Slide87 },
  { id: 's88', title: 'Interactivo: Flujo Train-Val-Test', section: '2.3. Ajuste de parámetros', component: Slide88 },
  { id: 's89', title: 'Validación Anidada', section: '2.3. Ajuste de parámetros', component: Slide89 },
  { id: 's90', title: 'Bucle Interno vs Externo', section: '2.3. Ajuste de parámetros', component: Slide90 },
  { id: 's91', title: 'Interactivo: Explorador Anidado', section: '2.3. Ajuste de parámetros', component: Slide91 },
  { id: 's92', title: 'Búsqueda de Hiperparámetros', section: '2.3. Ajuste de parámetros', component: Slide92 },
  { id: 's93', title: 'Resumen de Estrategias', section: '2.3. Ajuste de parámetros', component: Slide93 },
  { id: 's93a', title: 'Código: Curvas de Validación', section: '2.3. Ajuste de parámetros', component: Slide93a },
  { id: 's94', title: 'Quiz: Ajuste de Parámetros', section: '2.3. Ajuste de parámetros', component: Slide94 },
  { id: 's95', title: '2.4. Evaluación en Regresión', section: '2.4. Evaluación en regresión', component: Slide95 },
  { id: 's96', title: 'Error Absoluto Medio (MAE)', section: '2.4. Evaluación en regresión', component: Slide96 },
  { id: 's97', title: 'Error Cuadrático Medio (RMSE)', section: '2.4. Evaluación en regresión', component: Slide97 },
  { id: 's98', title: 'Error Porcentual (MAPE)', section: '2.4. Evaluación en regresión', component: Slide98 },
  { id: 's99', title: 'Coeficiente de Determinación (R²)', section: '2.4. Evaluación en regresión', component: Slide99 },
  { id: 's100', title: 'Interactivo: Calculadora de Errores', section: '2.4. Evaluación en regresión', component: Slide100 },
  { id: 's101', title: 'El Modelo Base (DummyRegressor)', section: '2.4. Evaluación en regresión', component: Slide101 },
  { id: 's102', title: 'Código: Evaluación en Regresión', section: '2.4. Evaluación en regresión', component: Slide102 },
  { id: 's103', title: 'Análisis Visual: Scatter Plot', section: '2.4. Evaluación en regresión', component: Slide103 },
  { id: 's104', title: 'Quiz: Evaluación en Regresión', section: '2.4. Evaluación en regresión', component: Slide104 },
  { id: 's105', title: '2.5. Evaluación en Clasificación', section: '2.5. Evaluación en clasificación', component: Slide105 },
  { id: 's106', title: 'Exactitud (Accuracy)', section: '2.5. Evaluación en clasificación', component: Slide106 },
  { id: 's107', title: 'La Matriz de Confusión', section: '2.5. Evaluación en clasificación', component: Slide107 },
  { id: 's108', title: 'Matriz de Confusión Binaria', section: '2.5. Evaluación en clasificación', component: Slide108 },
  { id: 's109', title: 'Interactivo: Matriz de Confusión', section: '2.5. Evaluación en clasificación', component: Slide109 },
  { id: 's110', title: 'Precisión (Precision)', section: '2.5. Evaluación en clasificación', component: Slide110 },
  { id: 's111', title: 'Sensibilidad (Recall)', section: '2.5. Evaluación en clasificación', component: Slide111 },
  { id: 's112', title: 'El Dilema: Precisión vs Sensibilidad', section: '2.5. Evaluación en clasificación', component: Slide112 },
  { id: 's113', title: 'Interactivo: El Umbral de Decisión', section: '2.5. Evaluación en clasificación', component: Slide113 },
  { id: 's114', title: 'F1-Score', section: '2.5. Evaluación en clasificación', component: Slide114 },
  { id: 's115', title: 'Capítulo 3. Regresión', section: '3.1. Regresión lineal múltiple', component: Slide115 },
  { id: 's116', title: '3.1. Regresión Lineal Múltiple', section: '3.1. Regresión lineal múltiple', component: Slide116 },
  { id: 's117', title: 'Mínimos Cuadrados Ordinarios (OLS)', section: '3.1. Regresión lineal múltiple', component: Slide117 },
  { id: 's118', title: 'Interpretación de Coeficientes', section: '3.1. Regresión lineal múltiple', component: Slide118 },
  { id: 's119', title: 'Descenso de Gradiente', section: '3.1. Regresión lineal múltiple', component: Slide119 },
  { id: 's120', title: 'La Tasa de Aprendizaje', section: '3.1. Regresión lineal múltiple', component: Slide120 },
  { id: 's121', title: 'Código: Regresión Lineal', section: '3.1. Regresión lineal múltiple', component: Slide121 },
  { id: 's121a', title: 'Código: Regresión Lineal Explicada', section: '3.1. Regresión lineal múltiple', component: Slide121a },
  { id: 's121b', title: 'Código: Guardar y Cargar Modelos', section: '3.1. Regresión lineal múltiple', component: Slide121b },
  { id: 's122', title: 'Ventajas de la Regresión Lineal', section: '3.1. Regresión lineal múltiple', component: Slide122 },
  { id: 's122a', title: 'Código: Regresión Polinómica', section: '3.1. Regresión lineal múltiple', component: Slide122a },
  { id: 's123', title: 'Hipótesis de la Regresión Lineal', section: '3.1. Regresión lineal múltiple', component: Slide123 },
  { id: 's124', title: 'Quiz: Regresión Lineal', section: '3.1. Regresión lineal múltiple', component: Slide124 },
  { id: 's125', title: 'Regularización: Ridge y Lasso', section: '3.1. Regresión lineal múltiple', component: Slide125 },
  { id: 's125a', title: 'Código: Regresión Regularizada', section: '3.1. Regresión lineal múltiple', component: Slide125a },
  { id: 's126', title: 'Interactivo: Ajuste Lineal', section: '3.1. Regresión lineal múltiple', component: Slide126 },
  { id: 's127', title: 'Hipótesis: Homocedasticidad', section: '3.1. Regresión lineal múltiple', component: Slide127 },
  { id: 's128', title: 'Hipótesis: Normalidad de Errores', section: '3.1. Regresión lineal múltiple', component: Slide128 },
  { id: 's129', title: 'Multicolinealidad', section: '3.1. Regresión lineal múltiple', component: Slide129 },
  { id: 's130', title: 'Métricas de Evaluación', section: '3.1. Regresión lineal múltiple', component: Slide130 },
  { id: 's131', title: 'Resumen: Regresión Lineal', section: '3.1. Regresión lineal múltiple', component: Slide131 },
  { id: 's132', title: 'Quiz: Regularización', section: '3.1. Regresión lineal múltiple', component: Slide132 },
  { id: 's133', title: 'Quiz: Hipótesis', section: '3.1. Regresión lineal múltiple', component: Slide133 },
  { id: 's134', title: 'Transición', section: '3.1. Regresión lineal múltiple', component: Slide134 },
  { id: 's135', title: '3.2. Vecinos Más Cercanos (KNN)', section: '3.2. Vecinos más cercanos', component: Slide135 },
  { id: 's136', title: 'La Premisa de KNN', section: '3.2. Vecinos más cercanos', component: Slide136 },
  { id: 's137', title: 'Los Dos Parámetros Clave', section: '3.2. Vecinos más cercanos', component: Slide137 },
  { id: 's138', title: 'Distancia de Minkowski', section: '3.2. Vecinos más cercanos', component: Slide138 },
  { id: 's139', title: 'Propiedades de la Distancia', section: '3.2. Vecinos más cercanos', component: Slide139 },
  { id: 's140', title: 'Cálculo de la Predicción', section: '3.2. Vecinos más cercanos', component: Slide140 },
  { id: 's141', title: 'Ponderación de Atributos', section: '3.2. Vecinos más cercanos', component: Slide141 },
  { id: 's142', title: 'La Importancia de la Escala', section: '3.2. Vecinos más cercanos', component: Slide142 },
  { id: 's143', title: 'Código: KNN Regressor', section: '3.2. Vecinos más cercanos', component: Slide143 },
  { id: 's143a', title: 'Código: KNN Regressor Explicado', section: '3.2. Vecinos más cercanos', component: Slide143a },
  { id: 's143b', title: 'Código: Búsqueda de Hiperparámetros', section: '3.2. Vecinos más cercanos', component: Slide143b },
  { id: 's144', title: 'Ventajas y Desventajas de KNN', section: '3.2. Vecinos más cercanos', component: Slide144 },
  { id: 's145', title: 'Interactivo: El efecto de K', section: '3.2. Vecinos más cercanos', component: Slide145 },
  { id: 's146', title: 'La Maldición de la Dimensionalidad', section: '3.2. Vecinos más cercanos', component: Slide146 },
  { id: 's147', title: 'Quiz: KNN Regresión', section: '3.2. Vecinos más cercanos', component: Slide147 },
  { id: 's148', title: 'Quiz: El parámetro K', section: '3.2. Vecinos más cercanos', component: Slide148 },
  { id: 's149', title: 'Resumen del Capítulo 3', section: '3.2. Vecinos más cercanos', component: Slide149 },
  { id: 's150', title: 'Transición', section: '3.2. Vecinos más cercanos', component: Slide150 },
  { id: 's151', title: 'Capítulo 4. Clasificación', section: '4.1. Regresión logística', component: Slide151 },
  { id: 's152', title: '4.1. Regresión Logística', section: '4.1. Regresión logística', component: Slide152 },
  { id: 's153', title: 'La Función Sigmoide', section: '4.1. Regresión logística', component: Slide153 },
  { id: 's154', title: 'Probabilidad y Umbral', section: '4.1. Regresión logística', component: Slide154 },
  { id: 's155', title: 'Entrenamiento: Log-Loss', section: '4.1. Regresión logística', component: Slide155 },
  { id: 's156', title: 'La Frontera de Decisión', section: '4.1. Regresión logística', component: Slide156 },
  { id: 's157', title: 'Clasificación Multiclase', section: '4.1. Regresión logística', component: Slide157 },
  { id: 's158', title: 'Código: Regresión Logística', section: '4.1. Regresión logística', component: Slide158 },
  { id: 's158a', title: 'Código: Regresión Logística Explicada', section: '4.1. Regresión logística', component: Slide158a },
  { id: 's159', title: 'Ventajas de la Regresión Logística', section: '4.1. Regresión logística', component: Slide159 },
  { id: 's160', title: 'Desventajas y Limitaciones', section: '4.1. Regresión logística', component: Slide160 },
  { id: 's161', title: 'Quiz: Regresión Logística', section: '4.1. Regresión logística', component: Slide161 },
  { id: 's162', title: 'Quiz: Estrategia Multiclase', section: '4.1. Regresión logística', component: Slide162 },
  { id: 's163', title: 'Resumen: Regresión Logística', section: '4.1. Regresión logística', component: Slide163 },
  { id: 's164', title: 'Transición', section: '4.1. Regresión logística', component: Slide164 },
  { id: 's165', title: '4.2. Árboles de Decisión', section: '4.2. Árboles de decisión', component: Slide165 },
  { id: 's166', title: 'Estructura Jerárquica', section: '4.2. Árboles de decisión', component: Slide166 },
  { id: 's167', title: 'Construcción del Árbol', section: '4.2. Árboles de decisión', component: Slide167 },
  { id: 's168', title: 'Índice Gini', section: '4.2. Árboles de decisión', component: Slide168 },
  { id: 's169', title: 'Fronteras de Decisión (CART)', section: '4.2. Árboles de decisión', component: Slide169 },
  { id: 's170', title: 'Código: Árbol de Decisión', section: '4.2. Árboles de decisión', component: Slide170 },
  { id: 's170a', title: 'Código: Árbol de Decisión Explicado', section: '4.2. Árboles de decisión', component: Slide170a },
  { id: 's170b', title: 'Código: Flujo Completo (Pipeline)', section: '4.2. Árboles de decisión', component: Slide170b },
  { id: 's171', title: 'Ventajas de los Árboles', section: '4.2. Árboles de decisión', component: Slide171 },
  { id: 's172', title: 'El Problema: Sobreajuste (Overfitting)', section: '4.2. Árboles de decisión', component: Slide172 },
  { id: 's173', title: 'Solución: Poda (Pruning)', section: '4.2. Árboles de decisión', component: Slide173 },
  { id: 's174', title: 'Interactivo: Crecimiento del Árbol', section: '4.2. Árboles de decisión', component: Slide174 },
  { id: 's175', title: 'Quiz: Árboles de Decisión', section: '4.2. Árboles de decisión', component: Slide175 },
  { id: 's176', title: 'Quiz: Poda', section: '4.2. Árboles de decisión', component: Slide176 },
  { id: 's177', title: 'Resumen: Árboles de Decisión', section: '4.2. Árboles de decisión', component: Slide177 },
  { id: 's178', title: 'Comparativa Final: Clasificación', section: '4.2. Árboles de decisión', component: Slide178 },
  { id: 's179', title: 'Resumen del Curso', section: '4.2. Árboles de decisión', component: Slide179 },
  { id: 's180', title: 'Fin del Módulo', section: '4.2. Árboles de decisión', component: Slide180 },
  { id: 's181', title: 'Variantes del Descenso de Gradiente', section: '3.1. Regresión lineal múltiple', component: Slide181 },
  { id: 's182', title: 'Elastic Net', section: '3.1. Regresión lineal múltiple', component: Slide182 },
  { id: 's183', title: 'Ingeniería de Atributos Lineal', section: '3.1. Regresión lineal múltiple', component: Slide183 },
  { id: 's184', title: 'Métricas: MAE vs MSE', section: '3.1. Regresión lineal múltiple', component: Slide184 },
  { id: 's185', title: 'Quiz: Descenso de Gradiente', section: '3.1. Regresión lineal múltiple', component: Slide185 },
  { id: 's186', title: 'Clasificación: One-vs-One (OvO)', section: '4.1. Regresión logística', component: Slide186 },
  { id: 's187', title: 'Entropía vs Gini', section: '4.2. Árboles de decisión', component: Slide187 },
  { id: 's188', title: 'Importancia de Atributos', section: '4.2. Árboles de decisión', component: Slide188 },
  { id: 's189', title: 'Datos Desbalanceados', section: '4.1. Regresión logística', component: Slide189 },
  { id: 's190', title: 'Quiz: Entropía vs Gini', section: '4.2. Árboles de decisión', component: Slide190 },
  { id: 's191', title: 'Resumen del Capítulo 4', section: '4.2. Árboles de decisión', component: Slide191 },
  { id: 's192', title: 'Gran Comparativa de Modelos', section: '4.2. Árboles de decisión', component: Slide192 },
  { id: 's193', title: 'Caso de Estudio: Diagnóstico', section: '4.2. Árboles de decisión', component: Slide193 },
  { id: 's194', title: 'Quiz Final: Selección de Modelo', section: '4.2. Árboles de decisión', component: Slide194 },
  { id: 's195', title: 'Quiz Final: Conceptos Globales', section: '4.2. Árboles de decisión', component: Slide195 },
  { id: 's196', title: 'El Futuro: Más Allá de lo Básico', section: '4.2. Árboles de decisión', component: Slide196 },
  { id: 's197', title: 'Consejos para el Científico de Datos', section: '4.2. Árboles de decisión', component: Slide197 },
  { id: 's198', title: 'Recursos Adicionales', section: '4.2. Árboles de decisión', component: Slide198 },
  { id: 's199', title: 'Conclusión Final', section: '4.2. Árboles de decisión', component: Slide199 },
  { id: 's200', title: '¡Gracias!', section: '4.2. Árboles de decisión', component: Slide200 },
];
